name: "Check Python Formatting"
on:
  push:
  pull_request:

permissions: read-all

concurrency:
  cancel-in-progress: true

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v